FASTOBJS = popstar_alg0.o imageOSX.o shellOSX.o
all: fast
%.o : %.mm
	$(CXX) $^ $(CPPFLAGS) -c -o $@ $(LDFLAGS) -DIOS
fast: $(FASTOBJS)
	$(CXX) $^ $(CPPFLAGS) -o $@ $(LDFLAGS) -DIOS -framework UIKit -framework CoreGraphics -framework Foundation

clean:
	rm -f *.o fast
